### ISSUE TITLE
Hide Admin Bar on Mobile

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsbcommons/reveal-js-presentations#2] opened 2015-11-03 17:37 UTC
the adminbar is obscuring the view on mobile. It would be good to hid the admin bar entirely with something like: 

```
    if (get_post_type ($post_id) == 'slides')
    {
        add_filter ('show_admin_bar', '__return_false');
```

We might need to account for the CSS margin on top as well, once we hide it. 

![img_4564](https://cloud.githubusercontent.com/assets/480667/10915976/2e099dc2-8227-11e5-8347-be04bdcf0740.PNG)

**Comment by r-a-y** [comment] 2015-11-04 17:55
Duplicate of #3.

**Closed as completed by r-a-y** 2015-11-04 17:55 UTC
